name: RealDeerking CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    environment: DEERKING

    env:
      HOST: ${{ secrets.ORACLE_EZEN_HOST }}
      USER: ${{ secrets.ORACLE_EZEN_USER }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ORACLE_EZEN_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          if [ -z "$HOST" ]; then
            echo "Error: HOST environment variable is not set"
            exit 1
          fi
          echo "Running ssh-keyscan for host: $HOST"
          ssh-keyscan "$HOST" >> ~/.ssh/known_hosts 2>/dev/null
      - name: Update Source Code on ORACLE
        run: |
          ssh $USER@$HOST << 'EOF'
            if [ ! -d /home/ubuntu/ezen-main-backend ]; then
              echo "Directory not found. Cloning repository..."
              git clone https://github.com/deerking0923/ezen-main-backend.git /home/ubuntu/ezen-main-backend
            else
              echo "Directory exists. Resetting and pulling latest changes..."
              cd /home/ubuntu/ezen-main-backend
              git reset --hard HEAD
              git pull
            fi
          EOF
      - name: Clean Maven Project
        run: |
          ssh $USER@$HOST "cd /home/ubuntu/ezen-main-backend && sudo mvn clean install -U"
      - name: Build Maven Project
        run: |
          ssh $USER@$HOST "cd /home/ubuntu/ezen-main-backend && sudo mvn package -DskipTests"

      - name: Build Docker Image
        run: |
          ssh $USER@$HOST "cd /home/ubuntu/ezen-main-backend && sudo docker build -t $DOCKER_USERNAME/ezen-main-backend:latest ."
  
      # - name: Push Docker Image
      #   run: |
      #     ssh $USER@$HOST "sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
      #     ssh $USER@$HOST "sudo docker push $DOCKER_USERNAME/ezen-main-backend:latest"
      - name: Deploy Application on ORACLE
        run: |
          ssh $USER@$HOST << 'EOF'
            # 기존 애플리케이션 종료
            sudo docker ps -q --filter "name=ezen-main-backend" | xargs -r sudo docker stop
            sudo docker ps -q --filter "name=ezen-main-backend" | xargs -r sudo docker rm
            sudo docker rmi $(sudo docker images -f "dangling=true" -q)
            sudo docker rm -f ezen-main-backend
            # 새 도커 컨테이너 실행
            sudo docker run -d --name ezen-main-backend -p 8080:8080 realdeer/ezen-main-backend:latest
            # 실행 확인
            sudo docker logs --tail 10 -f ezen-main-backend
          EOF
